[package]
name = "server"
version = "0.1.0"
authors = ["Minh Nguyen-Hue <minh.nh1989@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.1"
rocket_codegen = "0.4.1"
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"
r2d2 = "*"
r2d2-diesel = "*"
serde = "1.0.94"
serde_json = "1.0.39"
serde_derive = "1.0.94"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json"]
